FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /App


COPY . .
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /App
COPY --from=build-env /App/out .
COPY ./ports.conf /etc/apache2/ports.conf
COPY ./apache.conf /etc/apache2/sites-enabled/000-default.conf
ENTRYPOINT [ "dotnet","BBE-1.dll" ]